export const ADD_CONSTRUCTOR_INGREDIENT='ADD_CONSTRUCTOR_INGREDIENT';
export const DELETE_CONSTRUCTOR_INGREDIENT='DELETE_CONSTRUCTOR_INGREDIENT';
export const UPDATE_CONSTRUCTOR_INGREDIENTS='UPDATE_CONSTRUCTOR_INGREDIENTS';

export const ADD_MODAL_INGREDIENTS='ADD_MODAL_INGREDIENTS';
export const DELETE_MODAL_INGREDIENTS='DELETE_MODAL_INGREDIENTS';

export const REFRESH_ORDERDETAILS_ITEMS = 'REFRESH_ORDERDETAILS';

export const GET_INGREDIENTS_REQUEST = 'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_FAILED = 'GET_INGREDIENTS_FAILED';

export const GET_ORDERDETAILS_REQUEST = 'GET_ORDERDETAILS_REQUEST';
export const GET_ORDERDETAILS_SUCCESS = 'GET_ORDERDETAILS_SUCCESS';
export const GET_ORDERDETAILS_FAILED = 'GET_ORDERDETAILS_FAILED';

export const REFRESH_BUNS_SCROLL = 'REFRESH_BUNS_SCROLL';
export const REFRESH_SAUCES_SCROLL = 'REFRESH_SAUCES_SCROLL';
export const REFRESH_MAINS_SCROLL = 'REFRESH_MAINS_SCROLL';
